
name: Return status of pre-merge pipeline

on:
  workflow_run:
    workflows: ["pre-merge pipeline"]
    types: [completed]

jobs:
  check:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Return the result of the triggering workflow
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: check_status
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: ${{ github.event.workflow_run.conclusion }}
          output: |
            {"summary":"the status check for premerge pipeline"}
          details_url: ${{ github.event.repository.html_url }}/actions/runs/${{ github.event.workflow_run.id }}
