
name: Return status of pre-merge pipeline

on:
  pull_request:
    branches: ["master", "release"]
  workflow_run:
    workflows: ["pre-merge pipeline"]
    types: [completed]

jobs:
  check:
    runs-on: [ubuntu-latest]
    steps:
      - name: Return the result of the triggering workflow
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: check status
          conclusion: ${{ github.event.workflow_run.conclusion }}
          output: |
            {"summary":"hello"}
