
name: Return status of pre-merge pipeline

on:
  workflow_run:
    workflows: ["pre-merge pipeline"]
    types: [completed]

jobs:
  check:
    runs-on: [ubuntu-latest]
    permissions:
      checks: write
      contents: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Initialize the status check
        id: init
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.workflow_run.head_sha }}
          name: check_status
          status: in_progress
      - name: Update the status check
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.init.outputs.check_id }}
          conclusion: ${{ github.event.workflow_run.conclusion }}
          output: |
            {"summary":"See: ${{ github.event.repository.html_url }}/actions/runs/${{ github.event.workflow_run.id }}"}

