name: pre-merge pipeline

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read # required for action check-out repos
  id-token: write # required for action to access vault
  pull-requests: read  # required for action detecting changes in folders

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  skip_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.title == 'skip ci' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create commit for the PR
        run: |
          echo "testtesttest" > .version
          git config user.email "
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create commit for the PR
        run: |
          echo "testtesttest" > .version
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .version
          sleep 30
  final_job:
    needs: [skip_job, my_job]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create commit for the PR
        run: |
          echo "hello world"