name: Workflow Dispatch

on:
  workflow_dispatch

jobs:
  my_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create commit for the PR
        run: |
          echo "testtesttest" > .version
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .version
      - name: Open a PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: test
          title: Release title
          body: Release PR
